## Importing necessary libraries

In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
import joblib

## Importing resource and display

In [5]:
original_dataframe  = pd.read_csv('https://raw.githubusercontent.com/IT21034268/shared-location/refs/heads/other-data-01/student-performance-predictions/student_performance-01.csv')

In [6]:
edited_dataframe = original_dataframe

In [7]:
edited_dataframe.head(5)

Gender  AttendanceRate  AttendanceRateNormal  StudyHoursPerWeek  \
0       1              82                  0.48                 12   
1       1              85                  0.60                 15   
2       1              92                  0.88                 25   
3       0              90                  0.80                 20   
4       0              88                  0.72                 18   

   StudyHoursPerWeekNormal  PreviousGrade  ExtracurricularActivities  \
0                -0.877338             70                          2   
1                -0.415581             78                          1   
2                 1.123609             90                          3   
3                 0.354014             85                          2   
4                 0.046176             82                          2   

   ParentalSupport  FinalGrade  
0                0          72  
1                2          80  
2                2          92  
3                1          87  
4                1          85

In [8]:
model_01 = None
model_02 = None
model_03 = None

## Pre-Processing for `model_01`

In [9]:
columns_to_have_in_x = ['Gender', 'AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade', 'ExtracurricularActivities']
x = edited_dataframe[columns_to_have_in_x]

In [10]:
columns_to_have_in_y = ['ParentalSupport']
y = edited_dataframe[columns_to_have_in_y]

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [12]:
x_train_t = tf.convert_to_tensor(x_train)
x_test_t = tf.convert_to_tensor(x_test)


y_train_t = tf.convert_to_tensor(y_train)
y_test_t = tf.convert_to_tensor(y_test)

## `model_01` information

In [13]:
model_01 = None

In [14]:
x_var_count = len(columns_to_have_in_x)

In [15]:
x_var_count

5

In [16]:
# Set the random seed
tf.random.set_seed(42)

# Create the model
model_01 = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(x_var_count, )),
    tf.keras.layers.Dense(5, activation="relu"),
    tf.keras.layers.Dense(4, activation="relu"),
    tf.keras.layers.Dense(3, activation='softmax')
])

# Compile the model
model_01.compile(
                  loss=tf.keras.losses.SparseCategoricalCrossentropy(),
                  optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                  metrics=["accuracy"]
                )

# Fit the model
history_01 = model_01.fit(x_train_t, y_train_t, epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.2857 - loss: 1.0986
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.4286 - loss: 1.0968
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.4286 - loss: 1.0950
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4286 - loss: 1.0933
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 0.4286 - loss: 1.0917
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.4286 - loss: 1.0903
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.4286 - loss: 1.0889
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step - accuracy: 0.4286 - loss: 1.0876
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.4286 - loss: 1.0864
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.4286 - loss: 1.0853
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.4286 - loss: 1.0843
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step - accuracy: 0.4286 - loss: 1

In [17]:
# Save the model to a joblib file
filename = 'model_01.joblib'
with open(filename, 'wb') as file:
    joblib.dump(model_01, file)

In [18]:
# Open the saved joblib file
with open('model_01.joblib', 'rb') as file:
    model_01 = joblib.load(file)

In [19]:
model_01.evaluate(x_test_t, y_test_t)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 644ms/step - accuracy: 0.0000e+00 - loss: 1.2325


[1.2325429916381836, 0.0]

In [20]:
model_01.predict(x_test_t)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[0.2915502 , 0.41689962, 0.2915502 ],
       [0.2915502 , 0.41689962, 0.2915502 ],
       [0.2915502 , 0.41689962, 0.2915502 ]], dtype=float32)

## Pre-Processing for `model_02`

In [21]:
columns_to_have_in_x = ['Gender', 'AttendanceRateNormal', 'StudyHoursPerWeekNormal', 'PreviousGrade', 'ExtracurricularActivities']
x = edited_dataframe[columns_to_have_in_x]

In [22]:
columns_to_have_in_y = ['ParentalSupport']
y = edited_dataframe[columns_to_have_in_y]

In [23]:
y = pd.get_dummies(y['ParentalSupport'])

In [24]:
y

0      1      2
0   True  False  False
1  False  False   True
2  False  False   True
3  False   True  False
4  False   True  False
5   True  False  False
6  False   True  False
7   True  False  False
8  False  False   True
9  False  False   True

In [25]:
# y = y.applymap(lambda x: 1 if x else 0)

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [27]:
x_train_t = tf.convert_to_tensor(x_train)
x_test_t = tf.convert_to_tensor(x_test)


y_train_t = tf.convert_to_tensor(y_train)
y_test_t = tf.convert_to_tensor(y_test)

In [28]:
y_train_t = tf.cast(y_train_t, tf.int32)

In [29]:
y_test_t = tf.cast(y_test_t, tf.int32)

## `model_02` information

In [30]:
model_02 = None

In [31]:
x_var_count = len(columns_to_have_in_x)

In [32]:
x_var_count

5

In [33]:
# Set the random seed
tf.random.set_seed(42)

# Create the model
model_02 = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(x_var_count, )),
    tf.keras.layers.Dense(5, activation="relu"),
    tf.keras.layers.Dense(4, activation="relu"),
    tf.keras.layers.Dense(3, activation='softmax')
])

# Compile the model
model_02.compile(
                  loss=tf.keras.losses.CategoricalCrossentropy(),
                  optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                  metrics=["accuracy"]
                )

# Fit the model
history_02 = model_02.fit(x_train_t, y_train_t, epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.2857 - loss: 16.2390
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.2857 - loss: 15.1372
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.2857 - loss: 14.0652
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2857 - loss: 13.0226
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2857 - loss: 12.0093
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.2857 - loss: 11.0251
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2857 - loss: 10.0699
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2857 - loss: 9.1434
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2857 - loss: 8.2453
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.2857 - loss: 7.3753
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.2857 - loss: 6.5329
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.2857 - loss: 5.7

In [34]:
# Save the model to a joblib file
filename = 'model_02.joblib'
with open(filename, 'wb') as file:
    joblib.dump(model_02, file)

In [35]:
# Open the saved joblib file
with open('model_02.joblib', 'rb') as file:
    model_02 = joblib.load(file)

In [36]:
model_02.evaluate(x_test_t, y_test_t)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - accuracy: 0.0000e+00 - loss: 1.9269


[1.9269472360610962, 0.0]

In [37]:
model_02.predict(x_test_t)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[0.0551836 , 0.7686458 , 0.1761705 ],
       [0.06128217, 0.7581557 , 0.18056211],
       [0.09701803, 0.7037692 , 0.19921276]], dtype=float32)

## Pre-Processing for `model_03`

In [38]:
columns_to_have_in_x = ['AttendanceRateNormal', 'StudyHoursPerWeekNormal', 'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport']
x = edited_dataframe[columns_to_have_in_x]

In [39]:
columns_to_have_in_y = ['Gender']
y = edited_dataframe[columns_to_have_in_y]

In [40]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [41]:
x_train_t = tf.convert_to_tensor(x_train)
x_test_t = tf.convert_to_tensor(x_test)


y_train_t = tf.convert_to_tensor(y_train)
y_test_t = tf.convert_to_tensor(y_test)

## `model_03` information

In [42]:
model_03 = None

In [43]:
x_var_count = len(columns_to_have_in_x)

In [44]:
x_var_count

5

In [45]:
# Set the random seed
tf.random.set_seed(42)

# Create the model
model_03 = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(x_var_count, )),
    tf.keras.layers.Dense(5, activation="relu"),
    tf.keras.layers.Dense(4, activation="relu"),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model_03.compile(
                  loss=tf.keras.losses.BinaryCrossentropy(),
                  optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                  metrics=["accuracy"]
                )

# Fit the model
history_03 = model_03.fit(x_train_t, y_train_t, epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.4286 - loss: 17.3815
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4286 - loss: 14.9235
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4286 - loss: 12.5375
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4286 - loss: 10.2204
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4286 - loss: 7.9655
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4286 - loss: 5.7687
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4286 - loss: 3.6284
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4286 - loss: 1.6025
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7143 - loss: 0.6506
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5714 - loss: 1.4159
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5714 - loss: 2.2323
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5714 - loss: 2.7993

In [46]:
# Save the model to a joblib file
filename = 'model_03.joblib'
with open(filename, 'wb') as file:
    joblib.dump(model_03, file)

In [47]:
# Open the saved joblib file
with open('model_03.joblib', 'rb') as file:
    model_03 = joblib.load(file)

In [48]:
model_03.evaluate(x_test_t, y_test_t)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - accuracy: 0.3333 - loss: 1.7502


[1.750244140625, 0.3333333432674408]

In [49]:
model_03.predict(x_test_t)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


array([[0.01321053],
       [0.0356703 ],
       [0.14897203]], dtype=float32)